### ISSUE TITLE
[BUG] Scene change throws error with 3+ players and crash scene rendering

### ISSUE THREAD

**Issue by STBaf** [CDeenen/NotYourTurn#25]
Developer Issue:

NotYourTurn throws error with 3+ players to property scale.
This causes players tokens not rendered on scene.

foundry.js:37900 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'scale')
[No packages detected]
    at Token.refresh (foundry.js:37900:15)
    at Token._onUpdate (foundry.js:38670:12)
    at TokenDocument._onUpdate (foundry.js:9802:38)
    at TokenDocument._onUpdate (foundry.js:18997:18)
    at ClientDatabaseBackend.callback (foundry.js:10260:11)
    at foundry.js:10243:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:10243:33)
    at o.<anonymous> (foundry.js:9844:41)
    at o.T.emit (index.js:143:20)
    at o.value (socket.js:276:20)
    at o.value (socket.js:263:18)
    at o.value (socket.js:231:22)
    at s.T.emit (index.js:143:20)
    at s.value (manager.js:200:14)
    at a.T.emit (index.js:143:20)
    at a.value (index.js:105:51)
    at s.value (manager.js:192:22)
    at a.T.emit (index.js:143:20)
    at a.value (socket.js:323:26)
    at o.T.emit (index.js:143:20)
    at o.value (transport.js:99:14)
    at o.value (transport.js:92:14)
    at WebSocket.ws.onmessage (websocket.js:76:40)
refresh @ foundry.js:37900

**Comment by STBaf** [comment]
Fix didn't work really :(
